#!/bin/bash

counting=true

# If no parameters are passed, process all of stdin
if [[ "$#" -lt 1 ]]; then
	counting=false
fi

count=0

# process each of stdin
while read file
do
	# only if we are processing N files
	case $counting in
		(true)	# keep looping until N files are processed
			count=$((count + 1))
			if [[ $count -gt $1 ]]; then
				break;
			fi;;
	esac

	# process that line
	reencode_params -i "$file" -a aac -v libx265
done
