#!/bin/bash

for file in */*; do
    [ -f "$file" ] || continue
 	if [[ $(ffprobe -v quiet -print_format json -show_streams "$file" | grep -c 5.1) -gt 0 ]]; then
    	echo $file
	fi
done

for file in */*/*; do
    [ -f "$file" ] || continue
 	if [[ $(ffprobe -v quiet -print_format json -show_streams "$file" | grep -c 5.1) -gt 0 ]]; then
    	echo $file
	fi
done
