#!/bin/bash

# Default values
input=''
ext='mkv'
video='libx265'
audio='aac'
channels='2'
number='0'

print_usage() {
  printf "Usage: reencode -i FILE [arguments]
or: ls | reencode -i - [arguments]
  : reencode -i - [arguments] < file_list
to read from STDIN

-i FILE    File to reencode, '-' to use STDIN.
-n NUMBER  Number of files to encode if using STDIN. Not specifying will reencode all of the given files.
-e EXT     Use the file extension given for the output, e.g. avi. Default mkv.
-a CODEC   Use the audio codec to encode the file, e.g. copy. Default aac.
-v CODEC   Use the video codec to encode the file, e.g. copy. Default libx265.
-c         Number of audio channels to use. Default 2. Requires audio codec to not be copy.
-h         Print this message.
"
}

# Take a given file, reencode it with options from the arguments, then replace the file
reencode() {
  input="$1"
  temp="${input%.*}_tmp.${ext}"
  new="${input%.*}.${ext}"

  ffmpeg -i "$input" -y -map 0 -c:v "$video" -c:a "$audio" -ac "$channels" -c:s copy "$temp" &&
  rm "$input" &&
  mv "$temp" "$new";
}

# Get the command arguments
while getopts 'i:n:e:a:v:c:h' flag; do
  case "${flag}" in
    i) input="${OPTARG}" ;;
    n) number="${OPTARG}" ;;
    a) audio="${OPTARG}" ;;
    e) ext="${OPTARG}" ;;
    c) channels="${OPTARG}" ;;
    v) video="${OPTARG}" ;;
    h) print_usage exit 1 ;;
    *) print_usage exit 1 ;;
  esac
done

# Test if the input argument is STDIN or a file.
if [[ "$input" = '' ]]; then
    print_usage
elif [[ "$input" = "-" ]]; then
  while read file; do
    reencode "$file"

    # Decrease the number of files left to encode.
    # If it is == 0, all the files are done.
    # Default is starting at 0, which then becomes -1
    # So will never break if no number is specified.
    number=$((number - 1))
    if [[ $number -eq 0 ]]; then
      break
    fi
  done
else
  reencode "$input"
fi
