#!/bin/bash

input=''
ext='mkv'
video='copy'
audio='copy'
channels='2'

print_usage() {
	printf "Usage: reencode_params -i FILE [optional arguments]

-i FILE    File to reencode.
-e EXT     Use the file extension given for the output, e.g. avi. Default mkv.
-a CODEC   Use the audio codec to encode the file, e.g. aac. Default copy.
-v CODEC   Use the video codec to encode the file, e.g. libx265. Default copy.
-c         Number of audio channels to use. Default 2. Requires audio codec to not be copy.
-h         Print this message."
}

while getopts 'i:e:a:v:c:h' flag; do
	case "${flag}" in
  	i) input="${OPTARG}" ;;
  	a) audio="${OPTARG}" ;;
    e) ext="${OPTARG}" ;;
	c) channels="${OPTARG}" ;;
    v) video="${OPTARG}" ;;
	h) print_usage 
				exit 1 ;;
    *) print_usage
      	exit 1 ;;
  esac
done

if [ "$input" = '' ]; then
	print_usage
	exit 1
fi

temp="${input%.*}_tmp.${ext}"
new="${input%.*}.${ext}"

ffmpeg -i "$input" -y -map 0 -c:v "$video" -c:a "$audio" -ac "$channels" -c:s copy "$temp" &&
rm "$input" &&
mv "$temp" "$new";